version: "3.9"

services:
  app:
    image: webdevops/php-apache-dev:8.3
    container_name: caope_app
    working_dir: /app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_ALIAS_DOMAIN: localhost
    volumes:
      - ./backend:/app
    ports:
      - "8000:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes: {}
