name: Deploy to staging

on:
  push:
    tags:
      - 'staging-*'

permissions:
  contents: read

jobs:
  restore-test:
    name: Validate backup restoration
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: sqlite3, mysqli
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist
      - name: Prepare environment
        run: |
          cp .env.example .env
          sed -i 's/^DB_CONNECTION=.*/DB_CONNECTION=sqlite/' .env
          sed -i 's/^DB_DATABASE=.*/DB_DATABASE=database\/database.sqlite/' .env
          mkdir -p database
          touch database/database.sqlite
          php artisan key:generate
      - name: Generate database backup
        run: php artisan backup:run --only-db --no-interaction
      - name: Run backup restoration smoke tests
        run: |
          php artisan backup:test-restore-sqlite --no-interaction || exit 1
          php artisan backup:test-restore-mysql --no-interaction --allow-missing --allow-unavailable || exit 1

  deploy-staging:
    name: Deploy to staging server
    runs-on: ubuntu-latest
    needs: restore-test
    steps:
      - name: Execute staging deployment commands
        # Required secrets:
        #   STAGING_HOST    -> Hostname or IP address of the staging server
        #   STAGING_USER    -> SSH username used for the deployment
        #   STAGING_SSH_KEY -> Private SSH key for the user above
        # Optional secrets:
        #   STAGING_PORT    -> SSH port (defaults to 22 if unset)
        #   STAGING_PATH    -> Directory on the remote host where the app lives
        # Provide any additional secrets/environment variables the deployment script needs.
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          port: ${{ secrets.STAGING_PORT || 22 }}
          script: |
            # TODO: Replace `/ruta` with the correct deployment directory.
            # The tag name is available in the GITHUB_REF_NAME environment variable.
            cd "${{ secrets.STAGING_PATH || '/ruta' }}"
            git pull origin "${GITHUB_REF_NAME}"
            php artisan backup:run --only-db --no-interaction || true
            php artisan backup:test-restore-sqlite --no-interaction || true
            php artisan backup:test-restore-mysql --no-interaction || true
            # Add any other commands necessary to restart services, run migrations, etc.
