name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch, tag or commit to deploy'
        required: false
        default: main

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to production server
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    env:
      DEPLOY_REF: ${{ github.event_name == 'workflow_dispatch' && inputs.ref || 'main' }}
    steps:
      - name: Execute remote deployment commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT || 22 }}
          script: |
            cd "${{ secrets.DEPLOY_PATH }}"
            git fetch origin $DEPLOY_REF
            git checkout $DEPLOY_REF
            git pull origin $DEPLOY_REF
            ${{ secrets.DEPLOY_POST_COMMANDS }}
